export const ActionTypes = {
  //YÜKLENME DURUMUNU GÜNCELLEYECEK
  SET_LOADING: "SETLOADING",
  // ÜRÜNLERİ GÜNCELLEMEYE YARAYAN
  SET_PRODUCTS: "SET_PRODUCTS",
  // HATAYI GÜNCELLEMEYE YARAYAN
  SET_ERROR: "SET_ERROR",
  // BU ÜÇLÜ ÜRÜN VERİLERİNİ GÜNCELLEMEK İÇİN

  // SEPETİ GÜNCELLEMEYE YARAYAN  SEPETTEKİ VERİLER YÜKLENİYOR MU
  SET_BASKET_LOADING: "SET_BASKET_LOADING",
  //SEPETTEKİ VERİLER GÜNCELLENİYORSA SEPETİ GÜNCELLEMEYE YARAYAN
  SET_BASKET: "SET_BASKET",
  // SEPETTEKİ VERİLER YÜKLENMEDE GÜNCELLENMEDE HATA ALIRSAK ERROR
  SET_BASKET_ERROR: "SET_BASKET_ERROR",
  //SEPETE EKLEME
  ADD_TO_BASKET: "ADD_TO_BASKET",
  //SEPETİ GÜNCELLEME
  UPDATE_ITEM: "UPDATE_ITEM",
  // SEPETTEN KALDIRMA
  REMOVE_ITEM: "REMOVE_ITEM",

  // SEPET VERİLERİNİ GÜNCELLEMEYE YARAYAN SEPET AKSİYONLARI OLACAK
};
